version: '3'
services:
  demo:
    build:
      context: ./
      dockerfile: Dockerfile-build
    image: demoweb
    ports:
      - 8080
    networks:
      - network1
    scale: 3

networks:
  network1: